modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/davidjjung/sagebrush/issues"
license = "MIT License"

[[mods]]
modId = "sage_brush"
version = "${mod_version}"
logoFile = "logo.png"
itemIcon = "minecraft:brush"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = "DavigJ"
displayURL = "https://modrinth.com/mod/sage-brush"
displayName = "Sage Brush"
description = '''
    Wisens up brushes a bit.
    '''

[[dependencies.sage_brush]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sage_brush]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config="sage_brush.mixins.json"
